{% set name = "conquest" %}
{% set version = "1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/OrderN/CONQUEST-release/archive/v{{ version }}.tar.gz
  sha256: 5afddfee0d3c71580bcfc095acf52ccea116da3ba6887c2f6c5959ca7a2debbd
  patches:
    - system.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ stdlib("c") }}
    - make
    - perl
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - {{ mpi }}
    - libblas
    - liblapack
    - fftw
    - scalapack
    - libxc
  run:
    - scalapack

test:
  commands:
    - export OMPI_MCA_plm=isolated OMPI_MCA_btl_vader_single_copy_mechanism=none OMPI_MCA_rmaps_base_oversubscribe=yes OMPI_MCA_plm_ssh_agent=false  # [mpi == "openmpi"]
    - cd testsuite/test_001_bulk_Si_1proc_Diag
    - Conquest
  source_files:
    - testsuite/test_001_bulk_Si_1proc_Diag/Si.ion
    - testsuite/test_001_bulk_Si_1proc_Diag/coords.dat
    - testsuite/test_001_bulk_Si_1proc_Diag/Conquest_input

about:
  home: http://www.order-n.org
  summary: 'CONQUEST: Large-scale DFT calculations'
  description: |
    CONQUEST is a DFT code designed for large-scale calculations, with 
    excellent parallelisation. It gives a consistent, exact diagonalisation 
    approach for systems from 1 to 10,000+ atoms, and brings the possibility
    of linear scaling calculations on over 1,000,000 atoms. The code has 
    been demonstrated on scaling to nearly 200,000 cores and 2,000,000 atoms.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://conquest.readthedocs.io
  dev_url: https://github.com/OrderN/CONQUEST-release

extra:
  recipe-maintainers:
    - jan-janssen
